CREATE TABLE `tourist_info` (
`TouristID` int(255) PRIMARY KEY NOT NULL AUTO_INCREMENT,
`Email` varchar(64),
`Fullname` varchar(72),
`Contactno` varchar(11),
`Residence` varchar(16),
`Country` varchar(72),
`Region` varchar(16),
`Foreignerc` int(8),
`Filipinoc` int(8),
`Maubaninc` int(8),
`TotalV` int(8),
`TotalM` int(8),
`TotalF` int(8),
`TotalS`int(8),
`Sevenyold` int(8),
`Fifnineyold` int(8),
`Sixtyold` int(8),
`Arrivaldate` DATE,
`Itinerary` varchar(4),
`Resort`	varchar(8),
`Resortopt` varchar(64),
`Travelmeans` varchar(4),
`Parking` varchar(8),
`Parkingopt` varchar(64),
`Boating` varchar(8),
`Purpose` varchar(4),
`Purposeopt` varchar(64),
`Status` varchar(16)
);